config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create, :edit, :update, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' }, { id: 1, name: 'US$' }, { id: 2, name: 'CA$' },
    { id: 3, name: '€' }, { id: 4, name: 'MX$' }, { id: 5, name: 'R$' },
    { id: 6, name: 'CN¥' }, { id: 7, name: 'W' }, { id: 8, name: '฿' },
    { id: 9, name: 'Rp' }, { id: 10, name: '¥' }
  ]

  include ActiveHash::Associations
  has_many :rooms
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image

  validates :content, numericality: true, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :currency

  with_options presence: true do
    validates :name
    validates :manager
    validates :price, numericality: true, numericality: { message: 'は半角数字(カンマなし)で入力をしてください' }
  end
  validates :currency_id, numericality: { other_than: 0 , message: 'を選択してください'}

  def number
    @number = users.length
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth if Rails.env.production?
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to room_messages_path(@room)}
        format.json
      end
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    message = Message.find(params[:id])
    messages = @room.messages.includes(:user)
    if message.destroy
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new
  end

  def create

    @room = Room.new(room_params)
    if @room.save
      redirect_to room_messages_path(@room)
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to room_messages_path(@room)
    else
      render :edit
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, :price, :currency_id, user_ids: []).merge(manager: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>You owe me</title>
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
  <script>
    window.OneSignal = window.OneSignal || [];
    OneSignal.push(function() {
      OneSignal.init({
        appId: "c8b62ca9-c1c9-4047-96a8-333b29499055",
      });
    });
  </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="chat-title">
    <a href="/"><i class="fas fa-angle-left" id="to-group"></i></a>
    <%= link_to  @room.name, edit_room_path(@room.id), class: 'chat-title-name' %>
  </div>
    <% if @room.manager == current_user.id %>
      <div class="chat-close-btn">
        <%= link_to room_path(@room), id: 'delete-room-btn', :method => :delete do %>
          <i class="fas fa-door-open fa-1x"></i>
        <% end %>
      </div>
    <% end %>
</div>

<div class="messages" id= "messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', id:'form' do |f| %>
    <div class="form-input">
     <%= f.text_field :content , class: 'form-message', placeholder: '金額を入力して下さい', id: 'content' %>
     <%# <%= f.number_field :calculation , class: 'form-calculate', placeholder: '数値' %>
      <label class="form-image">
          <span class="image-file"><i class="fas fa-receipt fa-2x"></i></span>
          <%= f.file_field :image, class: 'hidden' %>
      </label>
    </div>
      <%= f.button :type => "submit", style: 'border-style: none;', id: 'form-submit' do %>
       <%# <%= f.submit '送信', class: 'form-submit', id: 'form-submit' %>
      <i class="far fa-paper-plane fa-2x"></i>
      <% end %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="right_content">
   <ul class="menu">
    <% if message.user_id == current_user.id  %>
      <li><a href=""><i class="fas fa-angle-down fa-2x"></i></a>
          <ul>
            <li><%= link_to '削除', room_message_path(@room, message) , method: :delete, class: "right_list" %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>

    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at, format: :short %>

    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <% if message.content %>
          <b><%= "支払額 #{@room.currency.name}" %><%= message.content.floor(2).to_s(:delimited) %></b><br>
        <% if @room.user_ids.length != 1 %>
          <b><%= "#{@room.number}人で割った1人分の金額は #{@room.currency.name}#{(message.content / @room.number).floor(2).to_s(:delimited)}" %></b>
        <% end %>
          <div class="lower-sub-message">
         <% if @room.currency_id != 10 %>
          <%= "支払いの換算額 ¥#{(message.content / @room.price * 100).floor(0).to_s(:delimited)}" %><br>
        <% end %>
        <% if @room.user_ids.length != 1 && @room.currency_id != 10 %>
          <%= "#{@room.number}人で割った1人分の換算額は ¥#{(message.content / @room.price * 100 / @room.number).floor().to_s(:delimited)}" %>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= image_tag message.image.variant(resize: '300x400'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-header">
  <div class="user-name">
    <%= link_to current_user.name, edit_user_path(current_user)%>
  </div>
  <div class="chat-create-btn">
    <a href="/rooms/new" class="create-btn">
      <i class="fas fa-user-friends fa-1x"></i>
    </a>
  </div>
</div>

  <div class="rooms">
    <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="group-name">
        <%= link_to room.name , room_messages_path(room) %>
      </div>
    </div>
    <% end %>
  </div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar" id="side-bar-none">
    <%= render "side_bar" %>
  </div>
  <div class="chat" id="chat-full">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class='chat-room-form'>
  <h1><i class="fas fa-user-friends fa-1x"></i>グループ編集</h1>
  <%=form_with model: @room, local: true do |f|%>
  <%= render 'shared/error_messages', model: @room %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :グループ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'グループ名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>メンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">ユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %> >
      </div>
      <%# チャットメンバー選択フォーム %>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">ユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">ユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
      </div>
    </div>
    <%# チャットメンバー選択フォーム %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :レート, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :price, class: 'chat__room_name chat-room-form__input', placeholder: '100円分の換算したい通貨を入れて下さい'%>
        <%= f.collection_select(:currency_id, Currency.all, :id, :name, {}, {class:"", id:""}) %>

      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit '作成',class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar" id="side-full">
    <%= render "messages/side_bar" %>
  </div>
  <div class=chat-screen>
  <img src="<%= asset_path "exchange-symbol.png" %>" alt="背景画面"  >
  <p>You owe meでシェアしたお金を秒速管理</p>
  <h3>さぁ、旅行を存分に楽しみましょう！</h3>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1><i class="fas fa-user-friends fa-1x"></i>グループ作成</h1>
  <%=form_with model: @room, local: true do |f|%>
  <%= render 'shared/error_messages', model: @room %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :グループ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'グループ名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>メンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">ユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %> >
      </div>
      <%# チャットメンバー選択フォーム %>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">ユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">ユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
      </div>
    </div>
    <%# チャットメンバー選択フォーム %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :レート, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :price, class: 'chat__room_name chat-room-form__input', placeholder: '100円分の換算したい通貨を入れて下さい'%>
        <%= f.collection_select(:currency_id, Currency.all, :id, :name, {}, {class:"", id:""}) %>

      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit '作成',class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>アカウントの編集</h2>
      
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "ページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "更新", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>